from sapk/cloud9

add ./get-docker.sh ./
run bash ./get-docker.sh
run apt-get update
run apt-get install -y \
    python python3 python-pip python3-pip
run pip install docker-compose

#run apt-get update
#run apt-get install -y \
#    apt-transport-https \
#    ca-certificates \
#    curl \
#    gnupg-agent \
#    software-properties-common
#run curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#run apt-key fingerprint 0EBFCD88
#run add-apt-repository \
#   "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable"
#run apt-get update   
#run apt-get install -y docker-ce docker-ce-cli containerd.io
